# Generated by Django 4.1.7 on 2023-04-06 12:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dob',
        ),
        migrations.AlterField(
            model_name='delivery_invoice',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 6, 19, 38, 17, 661239)),
        ),
        migrations.AlterField(
            model_name='import_invoice',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 6, 19, 38, 17, 660214)),
        ),
    ]
