<<<<<<< HEAD
# Generated by Django 4.2 on 2023-04-21 10:27
=======
# Generated by Django 4.2 on 2023-04-20 07:25
>>>>>>> 06a6c08d25b2606a9a7ba486c0d0fbf5df1f8845

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_invoice',
            name='time',
<<<<<<< HEAD
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 21, 17, 27, 49, 445749)),
=======
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 20, 14, 25, 14, 500427)),
>>>>>>> 06a6c08d25b2606a9a7ba486c0d0fbf5df1f8845
        ),
        migrations.AlterField(
            model_name='import_invoice',
            name='time',
<<<<<<< HEAD
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 21, 17, 27, 49, 445749)),
=======
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 20, 14, 25, 14, 498437)),
>>>>>>> 06a6c08d25b2606a9a7ba486c0d0fbf5df1f8845
        ),
        migrations.AlterField(
            model_name='motor',
            name='assurance',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='motor',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
