# Generated by Django 4.2 on 2023-04-24 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_delivery_invoice_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_invoice',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 25, 0, 16, 33, 362439)),
        ),
        migrations.AlterField(
            model_name='import_invoice',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 25, 0, 16, 33, 360445)),
        ),
    ]
