# Generated by Django 4.1.7 on 2023-04-07 07:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_delivery_invoice_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_invoice',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 7, 14, 19, 9, 968099)),
        ),
        migrations.AlterField(
            model_name='import_invoice',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 7, 14, 19, 9, 967093)),
        ),
    ]
