# Generated by Django 4.2 on 2023-04-25 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_delivery_invoice_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='delivery_invoice',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 26, 0, 9, 21, 907845)),
        ),
        migrations.AlterField(
            model_name='import_invoice',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 26, 0, 9, 21, 905851)),
        ),
    ]
